# Generated by Django 4.2.5 on 2023-09-14 11:28

from django.db import migrations, models
import frame.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Frame",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        validators=[frame.validators.frame_id_validator],
                    ),
                ),
                ("cam_id", models.IntegerField()),
                ("VideoColor", models.JSONField()),
                ("TimeSection", models.DateTimeField()),
                ("ChannelNo", models.IntegerField()),
                ("ConfigNo", models.IntegerField()),
            ],
            options={
                "db_table": "frame",
            },
        ),
        migrations.CreateModel(
            name="UserFrame",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("frame_id", models.IntegerField()),
            ],
            options={
                "db_table": "user_frame",
            },
        ),
    ]
